---
apiVersion: v1
kind: List
items:
{{- range .Values.Secrets }}
- apiVersion: v1
  kind: Secret
  metadata:
    name: {{ .name }}
    labels: 
{{ include "secrets.labels.stakater" $ | indent 6 }}
{{ include "secrets.labels.chart" $ | indent 6 }}
  data:
    {{- range $key, $value := .data }}
    {{ $key }}: {{ $value }}
    {{- end }}
  {{- if .type }}
  type: {{ .type }}
  {{- end }}
{{- end }}