---
apiVersion: v1
kind: List
items:
{{- range .Values.secrets.list }}
- apiVersion: v1
  data:
    {{- range .values }}
    {{ .key }}: {{ .value }}
    {{- end }}
  kind: Secret
  metadata:
    name: {{ .name }}
    labels: 
      chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
      release: {{ $.Release.Name | quote }}
      heritage: {{ $.Release.Service | quote }}
      version: {{ $.Chart.Version }}
  {{- if .type }}
  type: {{ .type }}
  {{- end }}
{{- end }}