secrets:
  namespace: default
  list:
    - name: someName
      values:
        - key: hello
          value: world
        - key: key2
          value: value2
      type: someType
    - name: secret2
      values:
        - key: someKey
          value: someValue